#!/bin/bash

ssh -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile /dev/null' -o 'LogLevel QUIET' -o 'ProxyCommand ssh -i ~/.ssh/gateway-key gateway.server nc %h %p 2>/dev/null' -i ~/.ssh/server-key ubuntu@$1
