#!/usr/bin/ruby

if ARGV[0] =~ /\.(tex|dvi|pdf|aux|log)/
    fileBaseName = ARGV[0].sub(/\.(tex|dvi|pdf|aux|log)/, "") 
elsif ARGV[0] =~ /\.$/
    fileBaseName = ARGV[0].sub(".", "") 
else
    fileBaseName = ARGV[0]
end

%x(
platex #{fileBaseName}
bibtex #{fileBaseName}
platex #{fileBaseName}
platex #{fileBaseName}
dvipdfmx #{fileBaseName}.dvi
rm -rf #{fileBaseName}.aux
rm -rf #{fileBaseName}.blg
rm -rf #{fileBaseName}.bbl
rm -rf #{fileBaseName}.log
rm -rf #{fileBaseName}.toc
rm -rf #{fileBaseName}.dvi
rm -rf texput.log
open -a Skim.app #{fileBaseName}.pdf
)
