#!/bin/bash


if [ $# -lt 1 ]
then
  echo "Usage: $0 j-XXXXXXXXXXXXX"
  exit
fi

cat << EOF
http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-web-interfaces.html
  1. YARN ResourceManager http://master-public-dns-name:8088/
  2. YARN NodeManager     http://slave-public-dns-name:8042/ (TODO)
  3. Hadoop HDFS NameNode http://master-public-dns-name:50070/
  4. Hadoop HDFS DataNode http://slave-public-dns-name:50075/ (TODO)
  5. Spark HistoryServer  http://master-public-dns-name:18080/
  6. Zeppelin             http://master-public-dns-name:8890/
  7. Hue                  http://master-public-dns-name:8888/
  8. Ganglia              http://master-public-dns-name/ganglia/ (TODO)
  9. HBase UI             http://master-public-dns-name:16010/

select [ENTER]:
EOF

read num
case "$num" in
  1) port=8088
    ;;
  3) port=50070
    ;;
  5) port=18080
    ;;
  6) port=8890
    ;;
  7) port=8888
    ;;
  9) port=16010
    ;;
  *) echo "undefined or not implemented yet" && exit 1
    ;;
esac


# http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-ssh-tunnel-local.html

master_public_dns_name=$(aws emr describe-cluster --cluster-id $1 | jrq -r '_.Cluster.MasterPublicDnsName')
LOCALPORT=8157

cmd=$(cat << EOF
ssh -i $HOME/.ssh/ec2-key.pem \
    -N \
    -L $LOCALPORT:$master_public_dns_name:$port \
    hadoop@$master_public_dns_name
EOF)
echo $cmd
echo "open http://localhost:$LOCALPORT/"

$($cmd)

