#!/bin/sh

if [ $# -eq 1 ]; then
    # git diff --no-ext-diff -- `git status -s -b | grep -v "^#" | awk '{print$1="";print}' | grep -v "^$" | awk "NR==$1"` | vim -R -
    git diff -- `git status -s -b | grep -v "^#" | awk '{print$1="";print}' | grep -v "^$" | awk "NR==$1"`
else
    exit 1
fi
