#!/bin/bash

TMP=$HOME/.tmp_say_tmux
tmux save-buffer $TMP

if [ -ne $TMP ]; then
  tmux display-message "Error: Cannot start speech."
  exit 1
fi

if which say > /dev/null 2>&1 ; then
  cat $TMP | say
else
  tmux display-message "Error: Cannot start speech."
  exit 1
fi
