#!/usr/bin/env ruby

def watch(start)
  t = (Time.now - start).to_i
  return "%02d:%02d" % [t / 60, t % 60] if t < 60 * 60
  "#{t / (60 * 60)}:#{"%02d:%02d" % [(t / 60) % 60, t % 60]}"
end

start_time = Time.now
begin
  while true
    output = watch(start_time)
    printf output
    printf "\e[#{output.size}D"
    STDOUT.flush
    sleep 1
  end
rescue Interrupt
  puts " -- stopped: #{watch(start_time)} (#{start_time} - #{Time.now})"
end
