#!/bin/sh
if [ $# -gt 1 ]; then
  skip=0; str=""
  for file in $*; do
    if [ $skip -eq 1 ]; then
      str="$str+'vs $file' "
    else
      skip=1
    fi
  done
  str2=`echo $str | sed -e s/\'/\"/g`
  # ...
  # TODO: many files at the same time...
  vim $1 +"vs $2"
else
  echo "usage: vvs file1 file2 ..."
  exit 1
fi
